kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: fGW7+qUybROwZaf3fG8LWZ+f3LyzkvSnCPJ3TlsQrdg=
      - identity: {}
