kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ejtxZg8ksBGsl+3Ecp2HZzLxpY5CY+tb44+O3uIAlPw=
      - identity: {}
